# Generated by Django 5.1.5 on 2025-06-02 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на русском')),
                ('name_kk', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на казахском')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Когда удалена запись')),
                ('code', models.CharField(blank=True, max_length=512, null=True, verbose_name='Код для внутреннего использования')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('deleted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Удалено работником')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено работником')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на русском')),
                ('name_kk', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на казахском')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Когда удалена запись')),
                ('short_name_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Сокращенное название на русском')),
                ('short_name_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Сокращенное название на английском')),
                ('short_name_kk', models.CharField(blank=True, max_length=128, null=True, verbose_name='Сокращенное название на казахском')),
                ('is_popular', models.BooleanField(blank=True, default=False, null=True, verbose_name='Популярный город для выбора')),
                ('is_default', models.BooleanField(blank=True, default=False, null=True, verbose_name='Регион по умолчанию')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код для внутреннего использования')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Действующий регион')),
                ('coordinates', models.JSONField(blank=True, null=True, verbose_name='Координаты границ региона')),
                ('coordinates_additional', models.JSONField(blank=True, null=True, verbose_name='Координаты границ региона (дополнительные)')),
                ('region_type', models.CharField(choices=[('REGION', 'Область'), ('CITY', 'Город'), ('DISTRICT', 'Район города')], default='CITY', max_length=32, verbose_name='Тип региона')),
                ('centroid', models.JSONField(blank=True, null=True, verbose_name='Центр региона')),
                ('layer_name', models.CharField(blank=True, null=True, verbose_name='Ссылка на дашбоард')),
                ('arcgis_id', models.CharField(blank=True, null=True, verbose_name='Уникальный ID из ARCGIS (OBJECTID)')),
                ('is_main', models.BooleanField(default=False, verbose_name='Город республиканского/ областного значения')),
                ('order_number', models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер для сортировки')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.country', verbose_name='Страна')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('deleted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Удалено работником')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='utils.region', verbose_name='Родительский регион')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено работником')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
    ]
