# Generated by Django 5.1.5 on 2025-01-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Оригинальное название')),
                ('hash_name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Хэшированное название')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Файл')),
                ('file_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='Физическое расположение файла')),
                ('mime_type', models.CharField(blank=True, max_length=512, null=True, verbose_name='Формат документа')),
                ('size', models.IntegerField(blank=True, default=0, null=True, verbose_name='Размер (кБ)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
